apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: learn-ingress
spec:
  rules:
  - host: myapp.linux.io
    http:
      paths:
      - backend:
          service:
            name: myapp-svc
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
